### ISSUE TITLE
Radar Improvement

### ISSUE THREAD

**Issue by HanaMcHanaface** [s-victor/TinyPedal#40]
Hello. Thank you for making this program it's very nice. 

A problem I have with the radar is that it shows other ppl position when in solo qualifying. Is there any chance of making it so they don't show up?

**Comment by s-victor** [comment]
Hi, there is an option in radar widget that auto hide radar when there is no nearby vehicle in radar range (this option is enabled by default). If it doesn't hide, double check or reset radar setting. Also, make sure spectate mode (spectate tab in main window) is not enabled.

**Comment by HanaMcHanaface** [comment]
Hello, sorry for the late response.

Yes I definitely mean the radar widget. I will explain better what I mean.

If you select "Private Qualifying" in settings, like this:

![2023_12_09_ 21 53 07](https://github.com/s-victor/TinyPedal/assets/113458072/7a7aced5-ff60-44fe-a501-3c35d0b208d0)

This means other drivers won't be visible to you when qualifying. However, the radar will still be active.

![2023_12_09_ 21 57 42](https://github.com/s-victor/TinyPedal/assets/113458072/cc0cbcbe-71fe-4f7a-94d9-60f7a7c82088)

It looks like this. As you can see, the radar shows that there's a car in front of you, even though there isn't. That's why I'm suggesting that TinyPedal radar should not have cars showing up when "Private Qualifying" is enabled.

**Comment by s-victor** [comment]
Hi, thanks for the explain. I understand this situation, this issue was actually mentioned a few times before.

The problem is that, private qualify is a special case where the game only hides opponent vehicles (and no collision) from the player who is driving. It does not remove or hide any data from API output(overlay info is fully based on API's output), and game API does not provide any data that determines whether it is private qualify session or not. So there is no native or "normal method" to automatically detect private qualify.

I know there is one possible but "hacky" method to get such info from other source, but it will not be reliable and there are other issues with it. So currently there is no viable way to improve it. However if I find new way to get around I'll let you know.

**Comment by HanaMcHanaface** [comment]
Aww that is too bad. Hope RF2 adds it at some point!! 😁

**Comment by HanaMcHanaface** [comment]
Very nice!! Haven't driven rfactor/LMU in a bit but hope to get back to it soon. Then I'll give it a try 😎
