### ISSUE TITLE
Improvement on widget Tyre wear

### ISSUE THREAD

**Issue by DanRZ** [s-victor/TinyPedal#45]
Hello, i just noticed there is an estimation of the lifespan of tyres.
It is really useful but nobody will us its Tyre to 0%.
Most of players have a good idea of their limit ... probably 50 ~ 60 % of Wear (Not sure).

It would be great if the estimated lap number in lifespan will take that in acount.
And give us the number of laps to get 50% (Parameter) of Wear ...
Maybe also add the options to switch laps/time.
It would be reaaly awesome to have that for endurance and evaluate stints on Tyre Wear.
Not a real issue but didn't find where to ask for improvements Here.

![Capture](https://github.com/s-victor/TinyPedal/assets/10159890/e7198d29-0a99-4acf-b8cf-f177a1bf3678)
Seconds or maybe minutes, more appropriate.

Thanks. This time i ask it Here ;)

**Comment by s-victor** [comment]
Thanks for the suggestion.

From my experience with leading an esports racing team, we usually hit the tyre grip limit at 10-20% remaining for WEC cars, which when the tyre wear drop below 20% or 10%, there will be a huge cliff performance drop. So 50% is actually far away from being at the limit.

I think the secs/mins/laps option switch is a good idea.

However the other suggestion that hides a portion of tyre lifespan may cause confusion to users. The reason is that, there are already many users used to this estimated laps calculation, if adding an option(or two, as how much percentage life span to hide also needs an extra option for different vehicles or preference) that hides portion of lifespan, those users would have to guess whether they have enabled this option or not (as you know every percentage matters in race). Of course they can check this setting before race, however as time passes, they may forgot what they have setting up, so this could become a tedious job that users have to always check setting to make sure they have the correct setting for the race to come. And users may also have to guess how much exactly those hidden portion of life span which they are likely want to know anyway.

So hiding portion of lifespan is probably not a good way, even if it is offered as an optional setting. It is best just let them know exactly how much they have left.

**Comment by s-victor** [comment]
ok, I just did an hour testing estimated lifespan in `minutes` at Sebring, and the result lacks a lot accuracy.

To calculate lifespan in minutes, the formula is:
Total remaining wear / last lap wear * last laptime / 60 seconds

As you can see, both `last lap wear` and `last laptime` can have big variance, this calculation would result even bigger lifespan variance in minutes (I got readings that varies as much as 5 to 10 mins difference). So it would not be useful to add lifespan in minutes display.

**Comment by DanRZ** [comment]
Thanks for the response and the explanations.
Hiding a part of the lifespan is really a bad idea. I agree.
The threshold and warning color change is a better way to do that more cleverly.
Nice way to notify the "short" lifespan.
I will try to produce a version and see how it works.
;)
