### ISSUE TITLE
In LMU, the trailing graph for the accelerator does not work (acc = 0 always)

### ISSUE THREAD

**Issue by duartevasco** [s-victor/TinyPedal#49]
![offline-FFB-drop-2](https://github.com/s-victor/TinyPedal/assets/838404/fc9d5291-559f-4d4c-bf3d-0869fd395f50)
In the image you can see that the accelerator is always at 0. 

Also, the pedal actuation is displayed correctly: half of the accelerator bar goes up when I press the pedal. However, it is never shown in the trailing graph, and the right half of the accelerator pedal display is also always zero

**Comment by s-victor** [comment]
Hi, if you have enabled **Show Raw Throttle** option, the main **Show Throttle** option must also be enabled to in order to show raw throttle plot, as **Show Throttle** option is the prerequisite of  **Show Raw Throttle** option, same applies to other plot.

**Comment by s-victor** [comment]
hi, I just did test on both LMH and GTE, and identified the problem. Since last LMU update, the GAME no longer output "filtered" throttle data from API for GTE cars. It now only output "raw" throttle data, this is why you only see the thin left part of throttle bar, which is the "raw" throttle data.

And Trailing Widget, by default, only show "filtered" throttle data, which is why you cannot see throttle plot on GTE. On the other hand, LMH hyper cars are still output "filtered" throttle data and working correctly.

What you can do is to also enable "Show Raw Throttle" option in Trailing widget, which will show raw pedal input and is working correctly at the moment.

As for "filtered" throttle data, since it is no longer output from API, there is nothing I can do about it, you may consider report this issue to official forum. The reason for it's output been disabled in GTE cars is unknown.

Again thanks for the heads up and letting me know the issue.
