### ISSUE TITLE
Incorrect fuel calculation in case of race end with delay on the first lap or more

### ISSUE THREAD

**Issue by mrlissandrello** [s-victor/TinyPedal#55]
calculation of remaining fuel is not correct in case of delay on the first position of one lap or more if the race does not end in time

**Comment by s-victor** [comment]
hi, that is not really an issue. Calculation is always based on your last lap time. Just ignore the readings from first lap.

There were some testing done earlier that to exclude first lap end lap laptime from fuel calculation, how it also has its own issue after extensive testing, which makes it not a good solution. Other solutions like calculating average laptime from past few laps were also tested, but they also have limitation and accuracy problem, such as under rain or other condition.

So currently there is no plan to change that.

**Comment by s-victor** [comment]
hi, that is not really an issue. Calculation is always based on your finishing position before timer end.

As for leader's "on track position" before timer end, there is a plan to implement a widget to estimate finishing position for both local player and leader (there is no estimation when it will be done). However the accuracy of such estimation can only be as close as it can get in the last stint, and there will be a lot variable affecting it. So in the end, it still up to user to determine whether leader will do an extra lap after race timer ended. Note, you can always simulate how many laps would be done with specific laptime(from leader) in Fuel Calculator before race.

**Comment by mrlissandrello** [comment]
I'm not talking about the time of the first lap.

I'm talking about the calculation of fuel left to finish the race in cases similar to the following:

20 drivers in the race and a 50-lap race.
The driver in 20th position was overlapped by the first one 2 times.
When the driver in first position finishes the 50th lap, for the driver in 20th position the last lap will be the 48th and not the 50th.
Currently TinyPedal calculates the remaining laps in the tank for the driver in 20th position as being 50. Instead, the laps to be calculated are 48.

**Comment by s-victor** [comment]
No, I was not talking about first lap.

I was exactly talking about **last lap after race timer end**. Please read my two earlier replies again, I have clearly explained how it calculates.

But in any case, to sum up again:
1. The fuel calculation only consider your laptime, your current on-track position, and when you will finish last lap.
2. Leader (driver in first position) is not considered in calculation, because it is not possible to know exactly when leader will start his last lap before **race timer end**. It can only be done by doing rough estimation (but there will be a lot variables that may not be accurate), which was explained in my last post, please read my [last post](https://github.com/s-victor/TinyPedal/issues/55#issuecomment-2227166717) again.

Let me know if you have further question.

**Comment by s-victor** [comment]
To make the example more clear:

Assume race setting has a race length of 18 minutes.

Assume your average lap time is 1:38.500. And Leader average lap time is 1:38.000, which is 0.5s faster than you per lap.

So in this case, the total laps when the moment race timer end (18mins count down) will be:
Leader total laps = 18mins x 60secs / 98.000secs(laptime) = 11.0204
Your total laps = 18mins x 60secs / 98.500secs(laptime) = 10.9644

Now because leader's total laps is 0.0204 above 11 laps, that means leader has just started his 12th lap 2 seconds (0.0204 x 98.000) before race time ended, so he has to finish this 12th lap to mark the end of race.

Then your total laps is just below 11 laps (10.9644), this means timer is ended before you have finished 11th lap. However since leader is ahead of you, and just started 12th lap as his final lap, you will also **have to do an extra final lap** for that exact reason. However, whether you have to do an extra lap or not, it still depends on the **relative on-track positions** between you and leader. For example, if leader can overtake you again on his 12th lap before you finish your 11th lap, then you will not need to do an extra lap.

The real situation will even more complex, that's why it is not possible to easily determine **whether you or leader will do an extra lap after race timer ended**. And that's what I'm planning to create a new widget to provide you & leader finishing position data, so you can use that as reference to decide whether to add extra fuel.

**Comment by s-victor** [comment]
ok, I probably misread your question, it seems you were taking about "lap-based" race instead of "time-based"?

If that is the case, then yes, tinypedal currently only calculates total laps and fuel from local player in both time-based & lap-based race types. If leader is faster and finishes total laps sooner, there will be less laps done for slow cars.

As I mentioned earlier that I plan to add widget to calculate and show leader finishing position, which may also be used to show estimated laps that leader will do, so it may help you determine whether you will need to carry less fuel (in your case, 2 laps of less fuel).

**Comment by s-victor** [comment]
The mentioned feature is now implemented and released in [v2.16.0 update](https://github.com/s-victor/TinyPedal/releases/tag/v2.16.0). See [forum post](https://forum.studio-397.com/index.php?threads/tinypedal-open-source-overlay-app-for-rf2-radar-pedal-ffb-deltabest-relative-fuel-calculator.71557/page-36#post-1145191) for full guide. Good luck.

**Comment by mrlissandrello** [comment]
thanks, as soon as i get back from holiday i will try it. btw how can i contribute financially to your business?

**Comment by s-victor** [comment]
no need, but thanks.
