### ISSUE TITLE
Global user config & path compatibility on linux

### ISSUE THREAD

**Issue by s-victor** [s-victor/TinyPedal#60]
@berarma @srlemke @alexbrrsclnt

As recently there is a request for auto loading preset depends on detected running sim from https://github.com/s-victor/TinyPedal/issues/58, and also add the ability to customize user folder path, I have implemented `global user config` in latest commits. The global user config file is called `config.json` and located in `~home/.config/TinyPedal/` folder. (`config.json` name was also now reserved and excluded from preset name)

In order to solve some issues and keep consistency, there is a change to default folder path for "settings".

On windows, the old default tinypedal user paths were (and not changed in new config):

    TinyPedal/
    TinyPedal/brandlogo/
    TinyPedal/deltabest/
    TinyPedal/settings/
    TinyPedal/trackmap/

And old linux paths were (`settings` folder was omitted in old version, and used the same TinyPedal folder):

    ~home/.config/TinyPedal/
    ~home/.local/share/TinyPedal/brandlogo/
    ~home/.local/share/TinyPedal/deltabest/
    ~home/.local/share/TinyPedal/trackmap/

Now with this new global user config, in order to keep code consistency, the default path for settings is now also located in `~home/.local/share/TinyPedal/settings` folder. It should be possible to add workaround to point to old default path, if that is necessary.

If you have preset from previous version, you either need to manually move all *.json from `~home/.config/TinyPedal/` to this new folder, or open `config.json` and edit default `settings_path` path to point to old path.

New UI config for easy accessing and editing `config.json` is currently in the work and will come later.

Feel free to let me know if any issue. There may be some changes needed to how default path should be handled on linux.

![settingspath](https://github.com/user-attachments/assets/41ab7420-db05-4a5c-9677-20200b94a47c)

**Comment by berarma** [comment]
In order to fully comply with the expectations for user dirs, I think I'd put settings into the config directory, but then I guess we should also put brand_logo_path there since this directory is filled by the user as part of the configuration.

Although maybe users prefer having everything in one place for easier access and backup. I don't want to complicate things by being too strict when we don't really need to be. Besides, since the locations can be changed in the config, if there's an inconvenience for someone they can change it.

So I think it's OK and maybe easier for the common user to have everything in one place.

**Comment by s-victor** [comment]
Good point, I'll see if I can put both `settings` & `brandlogo` folder in `./config/TinyPedal` folder instead. Let me know if you guys have further idea.

**Comment by s-victor** [comment]
Added new `User Path` config dialog in latest commits:
![pathdialog](https://github.com/user-attachments/assets/17bc1c3f-873e-40b9-899e-a403b44be9f6)
