### ISSUE TITLE
[RFE] support class wildcard

### ISSUE THREAD

**Issue by thoraxe** [s-victor/TinyPedal#62]
I'm currently racing in a series that has multiple "classes" but everything is being treated as the same class. There are two F3 chassis types that are slightly different, so RF2 treats them as different classes.

I'd like to be able to define a class with a wildcard, or do a partial match. This series has:

Tatuus F.3 T318 WSK
Tatuus F.3 T318 Asia

I'd like to be able to define a class as "Tatuus F.3*" because we are treating this as single-class racing.

**Comment by s-victor** [comment]
Wildcard was considered earlier, unfortunately it will not be added for reasons below:

The underlying mechanism in game is treating them as different classes, because they have different class name defined in mod's `VEH file`. And in final results, they are also marked and considered two different classes, and same thing if you run official broadcast overlay as multi class.

Treat them as same class externally by adding wildcard is basically useless, because either way they are treated differently internally in game as well as reflected on final results.

There is already an option provided to solve the exact situation: since both Tatuus are the same class, multi-class-split display is not required, you can just disable `Enable Multi Class Split Mode` option in Standings Widget, and disable other related options such as `show position in class`.

---

If however there is other vehicles that are completely different classes, for example with `2011 LMP1`, `2018 LMP1`, `2012 GT3`, `2020 GT3` all from different eras and modding teams with different classes name, then adding wildcard is also not an solution, because the same reasons:

They are internally marked as different classes, and shows in different classes in final results file(xml). Adding wildcard will only fool TinyPedal users, but not the game and final results. In that case, the common and real solution for league organizer, is to modify those mod VEH files to be the same classes so they are treated same in game and properly in final results, along with league BOP as usually required anyway.

Cheers

**Comment by s-victor** [comment]
By the way, no sure if you were aware, there are physics and performance differences between Asia & WSK version of F318, both car uses different physics HDV & tyre file. Usually leagues won't run both car in same race.

The differences were discussed in this thread:
https://forum.studio-397.com/index.php?threads/the-tatuus-pack-is-here.63469/page-7

And there was a specific physics adjustment to Asia version mentioned here:
https://www.studio-397.com/2021/10/released-tatuus-content-updates/

**Comment by thoraxe** [comment]
Somehow I failed to see the multi-class split option. Sorry for the noise!
