### ISSUE TITLE
[Fuel] Mins does not work

### ISSUE THREAD

**Issue by Cselt** [s-victor/TinyPedal#63]
I just realized that the minutes section of the fuel widget always shows 0.0.
It used to work nicely with previous version (maybe it was 2.18.0, can't tell unfortunately :( ).

![image](https://github.com/user-attachments/assets/da2be9ac-7cf8-4139-b6d2-c7986e552888)

**Comment by s-victor** [comment]
Hi, from the look of your screenshot, it seems that you haven't yet done a `valid lap time` in order to record a reference lap of `fuel data` from that session, this means values such as from `mins`, `delta`, `save`, `pits` columns cannot be calculated (because of missing reference data) until you have done at least one valid lap in that session to record the data, hence those mentioned columns in your screenshot are showing `0.00` readings.

Also noted that during start or pre-countdown phase of a race, those values may also not show because game API session data is not yet synchronized, and you have to wait until the race session actually starts its phase (such as formation, countdown, etc.)

**Comment by Cselt** [comment]
You are right I created the screenshot right after I started a session, but unfortunately doing a valid lap does not help for me still shows 0.0.

Here is a screenshot after 2 valid laps, and starting from pit:
![image](https://github.com/user-attachments/assets/6948dfce-f5c3-4f9a-aa46-0c68c774161f)

As it looks `delta` works nicely and I can see that value changing, but the others are 0.0.

**Comment by s-victor** [comment]
Check whether if you have all modules enabled. For example, fuel calculation depends on both Delta Module and Fuel Module. And make sure `Spectate` mode is disabled, if you are not sure, open Shared memory API config dialog, and click `Reset` then save. Also try reset both `Delta best` and `Fuel delta` from `Reset data` menu.

For your record, there hasn't been any change to fuel calculation or Fuel module since at least v2.17.0 as I just checked.

**Comment by Cselt** [comment]
Damn, you're right I checked and I had Delta Module turned off.

Sorry for the false alarm and thanks for your help :)

**Comment by s-victor** [comment]
no problem, happy driving
