### ISSUE TITLE
API shows game not running

### ISSUE THREAD

**Issue by K4ITHX** [s-victor/TinyPedal#66]
Hi, I've updated to the newest version but the overlay does not appear at all.
And I did check all plugins are in the right place.
In app it shows 'API: Le Mans Ultimate - not running' while in game.
Plz let me know what should I do to fix this, thank u.
![image](https://github.com/user-attachments/assets/6932d8ba-ddfc-48b0-942e-0b3b608fe498)

**Comment by s-victor** [comment]
Hi, please double check if `rFactor2SharedMemoryMapPlugin64.dll` plugin is correctly set to `" Enabled": 1` in `UserData\player\CustomPluginVariables.JSON` file (make sure game is closed while edit this file, otherwise it will have no effect).

Also note, this `API: Le Mans Ultimate - not running` line will only be updated if any preset or API has been reloaded, as it would be waste of system resource to constantly updating this line in the background. So there is no need to worry about this line if it shows `not running`.
