### ISSUE TITLE
TinyPedal working on Linux

### ISSUE THREAD

**Issue by berarma** [s-victor/TinyPedal#9]
Hi.

I have TinyPedal running on Linux pretty well after some changes to the code. There are some issues that could be changed with some more changes.

I want to create PR and I'm willing to support the tool on Linux. I can't help much with the Windows support because I don't have a Windows installation to test but I'm doing the changes to be as safe as possible for other platforms.

How do you feel about going cross-platform with TinyPedal?

To iron out the remaining issues I would need to do further changes to the code that would be easier if it got some refactorization to avoid duplication of code. Would you mind that I create PR for those refactorization changes too?

Thanks for this tool.

**Comment by s-victor** [comment]
Hello,

That is a very good news that you managed to make the app work on linux, and please feel free to open PR or do the changes as required.

And having cross-platform is good too. I can definitely help and testing code for windows platform. However since I don't use linux, providing support with linux related code will not be possible for me, so this will require your expertise (or others) if possible.

Thanks and let me know your opinion.

**Comment by berarma** [comment]
Of course, I want to help. I'll shortly make a first PR for the essential changes. We can discuss further changes later.

Thanks!

**Comment by s-victor** [comment]
Awesome, thanks!

**Comment by s-victor** [comment]
I have just managed to run the APP under fedora37 (LXDE spin), and noticed following things:
1. Tray icon menu doesn't work. After check pystray docs, know that pystray doesn't support menu under Xorg.
2. Left clicking interaction (default=True) also not working with LXDE's system tray, while [pystray docs here](https://pystray.readthedocs.io/en/latest/usage.html#getting-input-from-the-system-tray-icon) says it supports it under Xorg. I can only guess that maybe other "Desktop Environment" would work with this function, but not every DE.

Since both icon & menu interaction is not possible, I can't trigger the decoration issue you have mentioned.

My idea and solution is probably to create some kind of widget control panel window, then put all tray menu stuff into the panel window, where user can control widgets there. One of the advantages of having a panel window is that toggling widget would be much faster and easier.
The disadvantage is that this central control penal has to be visible all the time, and can't be locked.

**Comment by berarma** [comment]
> I have just managed to run the APP natively (not through wine) under fedora37 (LXDE spin), and noticed following things:
> 
>     1. Tray icon menu doesn't work. After check pystray docs, know that pystray doesn't support menu under Xorg.
> 
>     2. Left clicking interaction (default=True) also not working with LXDE's system tray, while [pystray docs here](https://pystray.readthedocs.io/en/latest/usage.html#getting-input-from-the-system-tray-icon) says it supports it under Xorg. I can only guess that maybe other "Desktop Environment" would work with this function, but not every DE.
> 
> 
> Since both icon & menu interaction is not possible, I can't trigger the [decoration issue](https://github.com/s-victor/TinyPedal/pull/10#issue-1533958168) you have mentioned.
> 
> My idea and solution is probably to create some kind of widget control panel window, then put all tray menu stuff into the panel window, where user can control widgets there. One of the advantages of having a panel window is that toggling widget would be much faster and easier.
> 
> The disadvantage is that this central control panel has to be visible all the time, and can't be locked(has to be always clickable by user), so this may not be an optimal solution. One way is to make the panel expandable and only interact with middle or right mouse click so that user won't accidentally activate something unwanted. This will need further investigation.
> 
> Nevertheless, there need to be a better way to exit APP on linux, as tray icon interaction is not possible on every distro (such as LXDE).

I have it working on Gnome with appindicator extension and others have used it with KDE. Your proposal would be the only solution for all desktop environments.

**Comment by s-victor** [comment]
Thanks for confirmation, I feel the same. I'll try create a widget control panel in the coming days and see how it works.

**Comment by srlemke** [comment]
Hello,

I have not tested it yet on openSUSE but have a question already:
When you run it nativelly, does it display the data properly? 

I'm asking because IIRC the shared memoty is 'locked' within the proton-vessel, so I wonder how tinypedal is able to 'read it'.

thanks!

**Comment by berarma** [comment]
> Hello,
> 
> I have not tested it yet on openSUSE but have a question already: When you run it nativelly, does it display the data properly?
> 
> I'm asking because IIRC the shared memoty is 'locked' within the proton-vessel, so I wonder how tinypedal is able to 'read it'.
> 
> thanks!

I didn't get to mention it but you need this rFactor 2 plugin: https://github.com/schlegp/rF2SharedMemoryMapPlugin_Wine

There's a compiled dll in the build directory.

It's a fork of the original plugin. The original plugin has to be disabled.

**Comment by srlemke** [comment]
Yeah that was the missing piece, working fine for me as well.

**Comment by s-victor** [comment]
hi guys,

I have just pushed a new update with new widget control menu (through preset manager), and all functions (including lock overlay) are working correctly under linux now.

You can find more info here:
https://forum.studio-397.com/index.php?threads/tinypedal-open-source-overlay-app-for-rf2-radar-pedal-ffb-deltabest-relative-fuel-calculator.71557/page-14#post-1119409

Lemme know for any issue & feedback.

Cheers

**Comment by berarma** [comment]
I'll test it as soon as I can and add the missing pieces. It's awesome the amount of work you put on all your projects. Thanks!

**Comment by alexbrrsclnt** [comment]
Awesome!! Thank you both very much!!

**Comment by berarma** [comment]
It's working very well, just one little issue that can be easily fixed. For some reason, setting the widget alpha (opacity) doesn't work unless it's executed after the call to `self.lift()`, at the very end of the `Base.init` method.

**Comment by s-victor** [comment]
Awesome, it's done, thanks!

**Comment by leillo1975** [comment]
@s-victor and @berarma , thanks a lot for bring to Linux this HUD. You make a great work and I'm very pleased to use it with rFactor 2. Yesterday I recorded a video with it, I hope you like it:
https://youtu.be/-sAz7f14rC8

Of course, I will follow this project and his updates. Cheers!

**Comment by Spacefreak18** [comment]
I have a couple projects which may be of interest. Particularly [my shared memory tool.](https://github.com/Spacefreak18/simshmbridge) It uses another project called [simapi](https://github.com/Spacefreak18/simaip), so that the goal is it can support unlimited sim titles. Right now, the code that's there for the simshmbridge is only for AC, but I've had RF2 working before, so i can add it as soon as possible.

**Comment by srlemke** [comment]
Just info for the unaware, recent commit may cause startup failure in Linux, at least on my distro, here fixed by installing pyxdg:
pip install pyxdg

**Comment by berarma** [comment]
> Just info for the unaware, recent commit may cause startup failure in Linux, at least on my distro, here fixed by installing pyxdg:
> pip install pyxdg

Yes. I have to write the instructions for Linux. We'll do it for next release hopefully.

**Comment by s-victor** [comment]
Hi, a quick notice, all player synced method including the linux related code from API submodule are separated into the file SimInfoSync.py https://github.com/s-victor/pyRfactor2SharedMemory/commit/47a0c6ea0c0883cd833b3a23161157f508296528 , both rF2data.py & sharedMemoryAPI.py were reverted back to be the same as upstream version.

This should help keep things unaffected from any future changes of the API (as RF2's recent update seems adding more API data). Remember to update submodule with new TinyPedal changes. Let me know if any issue.

**Comment by zapoutix** [comment]
Hi,

I have follow the instruction on the readme, by i have an issue when i try to run run.py, i take the master branch of 
pyRfactor2SharedMemory

`
[zapoutix@bakalinux TinyPedal-1.11.7]$ python run.py 
Traceback (most recent call last):
  File "/home/zapoutix/Downloads/TinyPedal-1.11.7/run.py", line 61, in <module>
    load_tinypedal()
  File "/home/zapoutix/Downloads/TinyPedal-1.11.7/run.py", line 53, in load_tinypedal
    from tinypedal.preset import LoadPreset
  File "/home/zapoutix/Downloads/TinyPedal-1.11.7/tinypedal/preset.py", line 32, in <module>
    from .readapi import info
  File "/home/zapoutix/Downloads/TinyPedal-1.11.7/tinypedal/readapi.py", line 42, in <module>
    info = SimInfoSync()
  File "/home/zapoutix/Downloads/TinyPedal-1.11.7/pyRfactor2SharedMemory/sim_info_sync.py", line 47, in __init__
    self.start_mmap()
  File "/home/zapoutix/Downloads/TinyPedal-1.11.7/pyRfactor2SharedMemory/sim_info_sync.py", line 64, in start_mmap
    self._rf2_tele = mmap.mmap(tele_file.fileno(), ctypes.sizeof(rF2data.rF2Telemetry))
ValueError: mmap length is greater than file size
setting saved
Exception ignored in: <function SimInfoSync.__del__ at 0x7fe02a58c820>
Traceback (most recent call last):
  File "/home/zapoutix/Downloads/TinyPedal-1.11.7/pyRfactor2SharedMemory/sim_info_sync.py", line 184, in __del__
    self.close()
  File "/home/zapoutix/Downloads/TinyPedal-1.11.7/pyRfactor2SharedMemory/sim_info_sync.py", line 89, in close
    self._rf2_tele.close()
AttributeError: 'NoneType' object has no attribute 'close'
`
I am using ArchLinux, with the lastest version of Rfactor2

i got all the $rFactor2SMMP_* then i do a ls /dev/shm

`
-rw-r--r--  1 zapoutix zapoutix    10152  1 avril 11:09 '$rFactor2SMMP_Extended$'
-rw-r--r--  1 zapoutix zapoutix       16  1 avril 11:09 '$rFactor2SMMP_ForceFeedback$'
-rw-r--r--  1 zapoutix zapoutix      272  1 avril 11:09 '$rFactor2SMMP_Graphics$'
-rw-r--r--  1 zapoutix zapoutix      116  1 avril 11:09 '$rFactor2SMMP_HWControl$'
-rw-r--r--  1 zapoutix zapoutix    39792  1 avril 11:09 '$rFactor2SMMP_MultiRules$'
-rw-r--r--  1 zapoutix zapoutix      340  1 avril 11:09 '$rFactor2SMMP_PitInfo$'
-rw-r--r--  1 zapoutix zapoutix       20  1 avril 11:09 '$rFactor2SMMP_PluginControl$'
-rw-r--r--  1 zapoutix zapoutix    45272  1 avril 11:09 '$rFactor2SMMP_Rules$'
-rw-r--r--  1 zapoutix zapoutix    45272  1 avril 11:09 '$rFactor2SMMP_RulesControl$'
-rw-r--r--  1 zapoutix zapoutix    75312  1 avril 11:09 '$rFactor2SMMP_Scoring$'
-rw-r--r--  1 zapoutix zapoutix   241680  1 avril 11:09 '$rFactor2SMMP_Telemetry$'
-rw-r--r--  1 zapoutix zapoutix      632  1 avril 11:09 '$rFactor2SMMP_Weather$'
-rw-r--r--  1 zapoutix zapoutix      628  1 avril 11:09 '$rFactor2SMMP_WeatherControl$'

`

Do you know how i can fix this issue .

Regards
Mathieu

**Comment by berarma** [comment]
> Hi,
> 
> I have follow the instruction on the readme, by i have an issue when i try to run run.py, i take the master branch of 
> pyRfactor2SharedMemory
> 
> 
> ```
> [zapoutix@bakalinux TinyPedal-1.11.7]$ python run.py 
> Traceback (most recent call last):
>   File "/home/zapoutix/Downloads/TinyPedal-1.11.7/run.py", line 61, in <module>
>     load_tinypedal()
>   File "/home/zapoutix/Downloads/TinyPedal-1.11.7/run.py", line 53, in load_tinypedal
>     from tinypedal.preset import LoadPreset
>   File "/home/zapoutix/Downloads/TinyPedal-1.11.7/tinypedal/preset.py", line 32, in <module>
>     from .readapi import info
>   File "/home/zapoutix/Downloads/TinyPedal-1.11.7/tinypedal/readapi.py", line 42, in <module>
>     info = SimInfoSync()
>   File "/home/zapoutix/Downloads/TinyPedal-1.11.7/pyRfactor2SharedMemory/sim_info_sync.py", line 47, in __init__
>     self.start_mmap()
>   File "/home/zapoutix/Downloads/TinyPedal-1.11.7/pyRfactor2SharedMemory/sim_info_sync.py", line 64, in start_mmap
>     self._rf2_tele = mmap.mmap(tele_file.fileno(), ctypes.sizeof(rF2data.rF2Telemetry))
> ValueError: mmap length is greater than file size
> setting saved
> Exception ignored in: <function SimInfoSync.__del__ at 0x7fe02a58c820>
> Traceback (most recent call last):
>   File "/home/zapoutix/Downloads/TinyPedal-1.11.7/pyRfactor2SharedMemory/sim_info_sync.py", line 184, in __del__
>     self.close()
>   File "/home/zapoutix/Downloads/TinyPedal-1.11.7/pyRfactor2SharedMemory/sim_info_sync.py", line 89, in close
>     self._rf2_tele.close()
> AttributeError: 'NoneType' object has no attribute 'close'
> ```
> 
> 
> I am using ArchLinux, with the lastest version of Rfactor2 (v1132)
> 
> i got all the $rFactor2SMMP_* then i do a ls /dev/shm
> 
> 
> ```
> -rw-r--r--  1 zapoutix zapoutix    10152  1 avril 11:09 '$rFactor2SMMP_Extended$'
> -rw-r--r--  1 zapoutix zapoutix       16  1 avril 11:09 '$rFactor2SMMP_ForceFeedback$'
> -rw-r--r--  1 zapoutix zapoutix      272  1 avril 11:09 '$rFactor2SMMP_Graphics$'
> -rw-r--r--  1 zapoutix zapoutix      116  1 avril 11:09 '$rFactor2SMMP_HWControl$'
> -rw-r--r--  1 zapoutix zapoutix    39792  1 avril 11:09 '$rFactor2SMMP_MultiRules$'
> -rw-r--r--  1 zapoutix zapoutix      340  1 avril 11:09 '$rFactor2SMMP_PitInfo$'
> -rw-r--r--  1 zapoutix zapoutix       20  1 avril 11:09 '$rFactor2SMMP_PluginControl$'
> -rw-r--r--  1 zapoutix zapoutix    45272  1 avril 11:09 '$rFactor2SMMP_Rules$'
> -rw-r--r--  1 zapoutix zapoutix    45272  1 avril 11:09 '$rFactor2SMMP_RulesControl$'
> -rw-r--r--  1 zapoutix zapoutix    75312  1 avril 11:09 '$rFactor2SMMP_Scoring$'
> -rw-r--r--  1 zapoutix zapoutix   241680  1 avril 11:09 '$rFactor2SMMP_Telemetry$'
> -rw-r--r--  1 zapoutix zapoutix      632  1 avril 11:09 '$rFactor2SMMP_Weather$'
> -rw-r--r--  1 zapoutix zapoutix      628  1 avril 11:09 '$rFactor2SMMP_WeatherControl$'
> ```
> 
> 
> Do you know how i can fix this issue .
> 
> Regards
> Mathieu

I have to try the newest version yet. Probably some recent change needs to be ported. Can you use an older version until I get to fix it?

I also want to write an install script to make it easier to install and update.

**Comment by berarma** [comment]
A fix is on the way.

For the future, I would open new issues instead of using this one for everything so I could reference them in other places.

I think this one can be closed since everything related to the port is already done.

**Comment by s-victor** [comment]
Thanks for help guys, I'll close this issue now.

**Comment by s-victor** [comment]
Hi, I'm reopening this issue as there are several features currently not working on Linux, which some may be interested to know the situation or help with the problem:

## LMU native sharedmemory API support on Linux

Since LMU 1.2 update, the game provides a native API, which no longer uses external plugins. While this is a positive step for the game, it does not work on Linux, as we know that windows & Linux use different sharedmemory accessing.

And while currently this new API is 99% same as old one (only a few minor differences that not related to driving data), it is however believed that the game's new API will eventually be upgraded later with more data, which may not be compatible with old plugins. So for Linux, it will likely need an alternative way to access LMU's native API eventually.

## Global hotkey support on Linux

As one of the most requested feature, "global hotkey support" is now implemented in commit https://github.com/TinyPedal/TinyPedal/commit/54a8d5ecee90cddbb830af71bb16751d9add1b6c, which currently works on Windows.

However, as discussed in some of the other issues, it could be difficult to support this feature for Linux, especially considering that there are multiple different display servers, notably `X11` & `Wayland` which they work very differently. While there are a few third-party libraries that seem to support "global hotkey", those may not be optimal and probably have their own limitations or does not work on certain display server. Also since the primary focus of TinyPedal is still on light-weight and efficiency, it will be best to keep as little dependency as possible unless there is not other choice.

---

Finally, as some of you already knew, since I don't use Linux, nor having a real setup for testing, there is very little I can help to add supports to those features for Linux. So it will really be up to other experienced Linux developers who may be interested in helping.

Thanks for any contributions.

Best luck

**Comment by Spacefreak18** [comment]
> Hi, I'm reopening this issue as there are several features currently not working on Linux, which some may be interested to know the situation or help with the problem:
> 
> ## LMU native sharedmemory API support on Linux
> Since LMU 1.2 update, the game provides a native API, which no longer uses external plugins. While this is a positive step for the game, it does not work on Linux, as we know that windows & Linux use different sharedmemory accessing.
> 
> And while currently this new API is 99% same as old one (only a few minor differences that not related to driving data), it is however believed that the game's new API will eventually be upgraded later with more data, which may not be compatible with old plugins. So for Linux, it will likely need an alternative way to access LMU's native API eventually.
> 
> ## Global hotkey support on Linux
> As one of the most requested feature, "global hotkey support" is now implemented in commit [54a8d5e](https://github.com/TinyPedal/TinyPedal/commit/54a8d5ecee90cddbb830af71bb16751d9add1b6c), which currently works on Windows.
> 
> However, as discussed in some of the other issues, it could be difficult to support this feature for Linux, especially considering that there are multiple different display servers, notably `X11` & `Wayland` which they work very differently. While there are a few third-party libraries that seem to support "global hotkey", those may not be optimal and probably have their own limitations or does not work on certain display server. Also since the primary focus of TinyPedal is still on light-weight and efficiency, it will be best to keep as little dependency as possible unless there is not other choice.
> 
> Finally, as some of you already knew, since I don't use Linux, nor having a real setup for testing, there is very little I can help to add supports to those features for Linux. So it will really be up to other experienced Linux developers who may be interested in helping.
> 
> Thanks for any contributions.
> 
> Best luck

For LeMans Ultimate, you can use the same modified plugin as RFactor2, and the shared memory will be available for native linux applications.

https://github.com/schlegp/rF2SharedMemoryMapPlugin_Wine

**Comment by s-victor** [comment]
TinyPedal was already utilizing the [modified wine version of RF2 plugin](https://github.com/schlegp/rF2SharedMemoryMapPlugin_Wine) since 3 years ago with the help from @berarma.

And since [v2.36.0](https://github.com/TinyPedal/TinyPedal/releases/tag/v2.36.0), a new "Le Mans Ultimate (legacy)" option (based on RF2 plugin) was added in API menu (meant for Linux users as fallback), which separates from LMU's new built-in API (no plugin).

The reason for separated API selection is because LMU's new native sharedmemory interface is not same as the old RF2 plugin, as the new API uses different structs and memory addresses, which requires different access methods.

For reference, you can find new API files in following game folder:
> Le Mans Ultimate\Support\SharedMemoryInterface

There are number of differences exist, where certain new data are already missing from old RF2 plugin. And the game developers are planning to update their new API with more data.

This means the new API will eventually be incompatible with old RF2 plugin in the future, even though old plugin continues to work (as of now), more API data may not be available through old RF2 plugin in future.

Currently, legacy option (as based on RF2 plugin) is still provided mainly for Linux user as a fallback.

Unfortunately, further maintenance will not likely be continued due to lack of maintainer and support from Linux user base.

**Comment by Spacefreak18** [comment]
so we're going to need hacks to access the new LMU shared memory like we have for Assetto Corsa.

do you know what exactly the existing RF2 data was missing that made them do this?

**Comment by s-victor** [comment]
RF2's "internals-plugin" headers in following link (Example Plugin v8):
https://www.studio-397.com/modding-resources/

Also this header is included in "rf2 shared memory map plugin" repo (may not be entirely same):
https://github.com/TheIronWolfModding/rF2SharedMemoryMapPlugin/blob/master/Include/InternalsPlugin.hpp

And LMU's "SharedMemoryInterface" headers from game folder:
> Le Mans Ultimate\Support\SharedMemoryInterface

And python implementation of those two API:  
https://github.com/s-victor/pyRfactor2SharedMemory/blob/master/rF2data.py
https://github.com/s-victor/pyLMUSharedMemory/blob/master/lmu_data.py (currently for windows only, because LMU built-in API does not output sharedmemory data to `/dev/shm/` as the wine ver. of RF2 Plugin. So ideally, we will likely need something similar to be able to output LMU built-in API memory block to `/dev/shm/`, which then we can use the same method to read data using native `mmap` on linux)

**Comment by s-victor** [comment]
Added support for reading sharedmemory data from "/dev/shm/" in pyLMUSharedMemory (https://github.com/s-victor/pyLMUSharedMemory/commit/4abb2fea415522d5a8aff93e6676bcc4dc59c971), same as how "pyRfactor2SharedMemory" was done before. However, this will not work until there is a plugin or app that can output LMU's built-in API memory data to a file in "/dev/shm/" (on windows, the current API file name is called "LMU_Data").

**Comment by Spacefreak18** [comment]
> Added support for reading sharedmemory data from "/dev/shm/" in pyLMUSharedMemory ([s-victor/pyLMUSharedMemory@4abb2fe](https://github.com/s-victor/pyLMUSharedMemory/commit/4abb2fea415522d5a8aff93e6676bcc4dc59c971)), same as how "pyRfactor2SharedMemory" was done before. However, this will not work until there is a plugin or app that can output LMU's built-in API memory data to a file in "/dev/shm/" (on windows, the current API file name is called "LMU_Data").

it should be relatively easy to add a new bridge exe to https://github.com/Spacefreak18/simshmbridge, I could work on it, but I don't have LMU to test.

**Comment by s-victor** [comment]
Thanks for your help, that's good news at least.

Unfortunately, I can't help testing either (only got vbox setup to do basic checks to make sure tinypedal don't break...).

Maybe some one sees this issue can help with test. I will add built-in API selection to tinypedal API menu meanwhile (just in case).

Good luck

---

Edit, LMU built-in API can now be selected on Linux (make sure to pull latest `pyLMUSharedMemory` submodule changes)

<img width="661" height="298" alt="Image" src="https://github.com/user-attachments/assets/d76ad523-7faf-4a4c-a6ea-6a9e11653b4c" />

**Comment by s-victor** [comment]
ok, since pyLMUSharedMemory now supports to read LMU built-in data from "/dev/shm/", the API read-access is considered to be done on TinyPedal's side for Linux.

Whether to utilize LMU built-in API and exporting its API data from WINE to "/dev/shm/LMU_Data" will be up to Linux user & dev. Case closed now, feel free to open new issue if needed.

Good luck

**Comment by s-victor** [comment]
Due to major API changes and large amount differences in LMU's 1.3 update, maintaining old "LMU legacy API" is no longer possible.

"LMU legacy API" will be deprecated and unmaintained from now on (and likely to be removed soon). Linux user should seek alternatives (such as those mentioned above) to use "LMU built-in API" instead.

Best luck

**Comment by Bykow** [comment]
Can we use this space this discuss solutions for Linux users with the new API ? 

@Spacefreak18 what is the current status of simshmbridge for LMU ?

**Comment by Spacefreak18** [comment]
> Can we use this space this discuss solutions for Linux users with the new API ?
> 
> [@Spacefreak18](https://github.com/Spacefreak18) what is the current status of simshmbridge for LMU ?

i have heard atleast two different people using it

**Comment by MarW1N** [comment]
> [@Spacefreak18](https://github.com/Spacefreak18) what is the current status of simshmbridge for LMU ?

@Bykow I'm using TinyPedal with simshmbridge and the script launch_lmu.sh and a environment file that contains the path to simshmbridge binaries and optional proton environment variables. Files available at

https://github.com/MarW1N/lmu-linux

The purpose of the launcher is to start and stop lmushm and lmubridge.exe automatically. Also has the added bonus of keeping steam options clean and easy to read since these variables live in the env file.

**Comment by Bykow** [comment]
@MarW1N Nice script ! 

~~Had a question, I don't have a `simshmbridge/bin` even after `make` (the `bin` is missing). Did I miss something ?~~

Got it, I was missing `mingw-w64-gcc` ...

**Comment by s-victor** [comment]
> @Bykow Can we use this space this discuss solutions for Linux users with the new API ?

Definitely, feel free to discuss and help, and good job to everyone getting it working on linux.

**Comment by Bykow** [comment]
@MarW1N I'm have trouble running your script, ~~it crashes before running the game, `simshmbridge` shows up and dies in 2-3s. The logs are not helpful I'm afraid~~

It crashes strait after a splashscreen, when the blackscreen shows up, then crash, with the error report window

**Comment by MarW1N** [comment]
@Bykow

Check launch_lmu.env, my Proton-variables might not suit you and may make your LMU crash. Modify environment-variables for Proton as it suits your system, or just comment all out if you normally don't use any when launching LMU.

Also, pushed a new script with some updated checks for missing binaries like the dependency to protontricks-launch etc that you can download as well. Commented out all Proton-variables as well per default.

**Comment by Spacefreak18** [comment]
> [@MarW1N](https://github.com/MarW1N) I'm have trouble running your script, ~it crashes before running the game, `simshmbridge` shows up and dies in 2-3s. The logs are not helpful I'm afraid~
> 
> It crashes strait after a splashscreen, when the blackscreen shows up, then crash, with the error report window

make sure you have the latest version of simshmbridge compiled. If that bridge exe doesn't allocate enough space this would happen.

**Comment by Bykow** [comment]
After multiple tries I'm unable to make it work. 

I have pull `simshmbridge` latest, built it. Edited the `env` file of the script from @MarW1N. But no luck. The game crashes after a small splash screen.

**Comment by MarW1N** [comment]
@Bykow Download latest version at https://github.com/MarW1N/lmu-linux and look at README.md how to enable debug logging. Also a bug fixed.
